[package]
name = "bevy_mod_outline"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A mesh outlining plugin for Bevy."
readme = "README.md"
homepage = "https://github.com/komadori/bevy_mod_outline/"
repository = "https://github.com/komadori/bevy_mod_outline/"
keywords = ["gamedev", "bevy", "outline"]
categories = ["game-engines", "rendering"]

[dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_asset",
    "render",
] }
libm = "0.2"

[dev-dependencies]
bevy = { version = "0.8", default-features = false, features = [
    "bevy_winit",
    "x11",
] }

[[example]]
name = "torus"
path = "examples/torus.rs"